// Edt-Vidt/src/app/presets/vista/vista.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-vista',
  templateUrl: './vista.component.html',
  styleUrls: ['./vista.component.scss']
})
export class VistaComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="vista">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
  <img class="vista__logo" src="../../../assets/img/vista.png">
</div>

// TypeScript/Edt-Vidt-old/src/views/vista/vista.component.vue
<template>
    <div class="vista">
        <img class="vista__logo" src="./vista.png" v-for="index in 40">
    </div>
</template>

<script lang="ts">
    import "./vista.scss";
    import Vue from "vue";
    import { Component } from "vue-property-decorator";

    @Component
    export default class VistaComponent extends Vue {
    }
</script>
