// TypeScript/Edt-Vidt/src/app/views/vista/vista.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'edt-vista',
    templateUrl: './vista.component.html',
    styleUrl: './vista.component.scss'
})
export class VistaComponent {
}

<div class="vista">
    @for (part of [].constructor(50); track part;) {
        <img class="vista__logo" src="./vista.png">
    }
</div>

// TypeScript/Edt-Vidt-old/src/views/vista/vista.component.vue
<template>
    <div class="vista">
        <img class="vista__logo" src="./vista.png" v-for="index in 40">
    </div>
</template>

<script lang="ts">
    import "./vista.scss";
    import Vue from "vue";
    import { Component } from "vue-property-decorator";

    @Component
    export default class VistaComponent extends Vue {
    }
</script>
