// TypeScript/Edt-Vidt/src/views/video-player/video-player.component.vue
<template>
    <div class="video">
        <video class="video__player" loop muted ref="video">
            <source type="video/mp4" v-bind:src="src">
            Your browser does not support the video tag.
        </video>

        <div class="video__overlay" v-if="overlay"></div>
    </div>
</template>

<script lang="ts">
    import './video-player.scss';
    import Vue from 'vue';
    import { Component } from 'vue-property-decorator';
    import { Actions$ } from '../../../../Shared/actions/actions';

    @Component
    export default class VideoPlayerComponent extends Vue {
        public beatSubscription: any;
        public videoSubscription: any;

        public src: string = '';
        public interval: number;
        public overlay = false;
        public $refs: {
            video: HTMLVideoElement;
        };

        mounted() {
            this.videoSubscription = Actions$.videoSrc.subscribe(
                (video: string) => {
                    this.setSrc(video);
                    this.playVideo();
                },
            );

            this.beatSubscription = Actions$.mainBeat.subscribe(() => {
                this.glitchVideo();
            });
        }

        setSrc(src: string) {
            this.src = `assets/videos/${src}`;
        }

        playVideo() {
            if (this.interval) {
                clearInterval(this.interval);
            }
            this.$refs.video.load();
            this.$refs.video.muted = true; // fix for muted attr bug
            this.$refs.video.play();
        }

        glitchVideo() {
            if (this.interval) {
                clearInterval(this.interval);
            }

            this.$refs.video.currentTime =
                Math.random() * this.$refs.video.duration;
        }

        glitchVideoContinuous() {
            this.interval = window.setInterval(() => {
                this.$refs.video.currentTime =
                    Math.random() * this.$refs.video.duration;
            }, 1000);
        }

        destroyed() {
            if (typeof this.beatSubscription !== 'undefined') {
                this.beatSubscription.unsubscribe();
            }

            if (typeof this.videoSubscription !== 'undefined') {
                this.videoSubscription.unsubscribe();
            }

            if (this.interval) {
                clearInterval(this.interval);
            }
        }
    }</script>

// Edt-Vidt/src/app/presets/video-player/video-player.component.ts
import {Component, ElementRef, OnInit, ViewChild} from '@angular/core';
import {IVideoAsset, videoAssets} from '../../../data/assets';

@Component({
  selector: 'app-video-player',
  templateUrl: './video-player.component.html',
  styleUrls: ['./video-player.component.scss']
})
export class VideoPlayerComponent implements OnInit {
    @ViewChild('videoplayer') videoplayer: any;

    private interval;
    public video: IVideoAsset;

    constructor(private element: ElementRef) {
    }

    ngOnInit() {
        // todo change video nr with ipad
       this.switchVideo(0);

        if (this.video !== undefined) {
            this.playVideo();
        }
    }

    playVideo() {
        if (this.interval) {
            clearInterval(this.interval);
        }

        this.videoplayer.nativeElement.muted = true; // fix for muted attr bug
        this.videoplayer.nativeElement.play();

        if(this.video.glitch) {
            this.interval = setInterval(() => {
                this.videoplayer.nativeElement.currentTime = Math.random() * this.videoplayer.nativeElement.duration;
            }, 1000);
        }
    }

    switchVideo(videoIndex: number) {
        const video = videoAssets[videoIndex];
        if (!video) {
            this.video = videoAssets[0]
        } else {
            this.video = video;
        }
    }

    ngOnDestroy() {
        clearInterval(this.interval);
    }
}

<div class="video">
    <video class="video__player" #videoplayer muted loop>
        <source *ngIf="video && video.src" src="/assets/video/{{ video.src }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>

    <div *ngIf="video && video.effectOverlay" class="video__overlay"></div>
</div>
