// TypeScript/Edt-Vidt/src/views/color-twinkle/color-twinkle.component.vue
<template>
    <div class="color-twinkle">
        <div class="color-twinkle__star" v-bind:style="styles" v-for="star in stars">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</template>

<script lang="ts">
    import './color-twinkle.scss';

    import Vue from 'vue';
    import { Component } from 'vue-property-decorator';
    import { Actions$ } from '../../../../Shared/actions/actions';
    import { IColor } from '../../../../Shared/types';
    import { ColorHelper } from '../../../../Shared/colors/converters';

    @Component
    export default class ColorTwinkleComponent extends Vue {
        public colorSubscription: any;
        public styles: Object = {};
        public $refs: {
            color: HTMLElement;
        };

        public stars: number[] = Array(400).map((x, i) => i + 1);

        mounted() {
            this.colorSubscription = Actions$.vidtSingleColor.subscribe(item => {
                this.setStyles(item);
            });
        }

        setStyles(hsb: IColor) {
            this.styles = {
                color: ColorHelper.getRGBString([hsb]),
            };
        }

        destroyed() {
            if (typeof this.colorSubscription !== 'undefined') {
                this.colorSubscription.unsubscribe();
            }
        }
    }
</script>

// TypeScript/Edt-Vidt/src/app/views/color-twinkle/color-twinkle.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { IColor } from '../../../../../Shared/colors/types';
import { ColorHelper } from '../../../../../Shared/colors/converters';
import { Actions$ } from '../../../../../Shared/actions/actions';

const AMOUNT_OF_STARS = 400;

@Component({
    selector: 'edt-color-twinkle',
    templateUrl: './color-twinkle.component.html',
    styleUrl: './color-twinkle.component.scss',
})
export class ColorTwinkleComponent implements OnInit, OnDestroy {
    public styles: Object = {};

    private readonly destroyed = new Subject();
    stars = new Array(AMOUNT_OF_STARS).fill(0).map((_, i) => i);

    public ngOnInit() {
        Actions$.vidtSingleColor.pipe(takeUntil(this.destroyed)).subscribe((item) => {
            this.setStyles(item);
        });
    }

    public ngOnDestroy() {
        this.destroyed.next(true);
        this.destroyed.complete();
    }

    public setStyles(hsb: IColor) {
        this.styles = {
            color: ColorHelper.getRGBString([hsb]),
        };
    }
}

<div class="color-twinkle">
    @for (star of stars; track star;) {
        <div class="color-twinkle__star" [style]="styles">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    }
</div>
