// TypeScript/Edt-Vidt/src/app/app.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { Router } from '@angular/router';
import { VidtPresets } from '../../../Shared/vidt-presets';
import { Actions$ } from '../../../Shared/actions/actions';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
    private readonly destroyed = new Subject();
    private readonly router = inject(Router);
    public ngOnInit() {
        // this['sockets'].subscribe('toVidt', nextActionFromMsg);
        //
        // Actions$.prepareVidt
        //     .pipe(takeUntil(this.destroyed))
        //     .subscribe((preset: number) => {
        //         this.router.navigate([VidtPresets[preset]]);
        //     });
    }

    public ngOnDestroy() {
        this.destroyed.next(true);
        this.destroyed.complete();
    }
}

// TypeScript/edt-vidt2/src/App.vue
<template>
    <router-view/>
</template>

<script lang="ts">
    import { Actions$ } from "../../Shared/actions";
    import router from "./router";
    import { VidtPresets } from "../../Shared/vidt-presets";

    import { Component } from "vue-property-decorator";
    import Vue from "vue";

    @Component
    export default class App extends Vue {
        public subscription: any;

        mounted() {
            this.subscription = Actions$.prepareVidt.subscribe(
                (preset: number) => {
                    router.push({path: "/" + VidtPresets[preset]});
                },
            );
        }

        destroyed() {
            if (typeof this.subscription !== "undefined") {
                this.subscription.unsubscribe();
            }
        }
    }
</script>

<style lang="scss">
    @import "./scss/layout";
</style>
