// Edt-Vidt/src/app/presets/shutdown/shutdown.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-shutdown-component',
  templateUrl: './shutdown.component.html',
  styleUrls: ['./shutdown.component.scss']
})
export class ShutdownComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="shutdown">
  <div class="shutdown__text">format c:</div>
</div>

// TypeScript/Edt-Vidt-old/src/views/shutdown/shutdown.component.vue
<template>
    <div class="shutdown">
        <div class="shutdown__text">format c:</div>
    </div>
</template>

<script lang="ts">
    import "./shutdown.scss";
    import Vue from "vue";
    import { Component } from "vue-property-decorator";

    @Component
    export default class ShutdownComponent extends Vue {
    }
</script>
