// Edt-Vue-Vidt/src/typescript/presets/video-player/video-player.component.ts
import Vue from 'vue';
import {Component} from 'vue-property-decorator';
import {IVideoAsset} from '../../../../../Shared/assets';
import {Actions$} from '../../../../../Shared/actions';

@Component({
    name: 'video-player',
    template: require('./video-player.template'),
    components: {
    }
})

export class VideoPlayerComponent extends Vue {
    public beatSubscription: any;
    public videoSubscription: any;

    public src: string = '';
    public interval: number;
    public overlay: boolean = true;
    public $refs : {
        video: HTMLVideoElement
    };

    mounted() {
        this.videoSubscription = Actions$.videoSrc
            .subscribe((video: IVideoAsset) => {
                this.setSrc(video.src);
                this.setOverlay(video.overlay);
                this.playVideo();
            });

        this.beatSubscription = Actions$.mainBeat
            .subscribe(() => {
                this.glitchVideo();
            });
    }

    setSrc(src: string) {
        this.src = `assets/video/${src}`;
    }

    setOverlay(state: boolean) {
        this.overlay = state;
    }

    playVideo() {
        if (this.interval) {
            clearInterval(this.interval);
        }
        this.$refs.video.load();
        this.$refs.video.muted = true; // fix for muted attr bug
        this.$refs.video.play();
    }

    glitchVideo() {
        if (this.interval) {
            clearInterval(this.interval);
        }

        this.$refs.video.currentTime = Math.random() * this.$refs.video.duration;
    }

    glitchVideoContinuous() {
        this.interval = window.setInterval(() => {
            this.$refs.video.currentTime = Math.random() * this.$refs.video.duration;
        }, 1000);
    }

    destroyed() {
        if (typeof this.beatSubscription !== 'undefined') {
            this.beatSubscription.unsubscribe();
        }

        if (typeof this.videoSubscription !== 'undefined') {
            this.videoSubscription.unsubscribe();
        }

        if (this.interval) {
            clearInterval(this.interval);
        }
    }
}

// TypeScript/Edt-Vidt/src/app/views/video-player/video-player.component.ts
import { AfterContentInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { Actions$ } from '../../../../../Shared/actions/actions';

@Component({
    selector: 'edt-video-player',
    templateUrl: './video-player.component.html',
    styleUrl: './video-player.component.scss',
})
export class VideoPlayerComponent implements AfterContentInit, OnDestroy {
    public src: string = '';
    public interval?: number;
    public overlay = false;
    @ViewChild('video') videoRef?: ElementRef<HTMLVideoElement>;
    private readonly destroyed = new Subject();

    public ngAfterContentInit() {
        Actions$.videoSrc.pipe(takeUntil(this.destroyed)).subscribe((video: string) => {
            this.setSrc(video);
            this.playVideo();
        });

        Actions$.mainBeat.pipe(takeUntil(this.destroyed)).subscribe(() => {
            this.glitchVideo();
        });
    }

    public ngOnDestroy() {
        this.destroyed.next(true);
        this.destroyed.complete();
    }

    setSrc(src: string) {
        this.stopVideo();
        this.src = `./assets/media-by-group/${src}`;
    }

    playVideo() {
        if (this.interval) {
            clearInterval(this.interval);
        }

        if (this.videoRef) {
            this.stopVideo();

            this.videoRef.nativeElement.load();
            this.videoRef.nativeElement.addEventListener('loadedmetadata', () => {
                if (this.videoRef) {
                    this.videoRef.nativeElement.currentTime = Math.random() * this.videoRef.nativeElement.duration;
                }
            });
            this.videoRef.nativeElement.muted = true; // fix for muted attr bug
            this.videoRef.nativeElement.play();
        }
    }

    glitchVideo() {
        if (this.interval) {
            clearInterval(this.interval);
        }

        if (this.videoRef) {
            this.videoRef.nativeElement.currentTime = Math.random() * this.videoRef.nativeElement.duration;
        }
    }

    glitchVideoContinuous() {
        if (!this.videoRef) {
            return;
        }

        this.interval = window.setInterval(() => {
            if (this.videoRef) {
                this.videoRef.nativeElement.currentTime = Math.random() * this.videoRef.nativeElement.duration;
            }
        }, 1000);
    }

    stopVideo() {
        if (this.videoRef) {
            const isPlaying =
                this.videoRef.nativeElement.currentTime > 0 &&
                !this.videoRef.nativeElement.paused &&
                !this.videoRef.nativeElement.ended &&
                this.videoRef.nativeElement.readyState > this.videoRef.nativeElement.HAVE_CURRENT_DATA;
            if (isPlaying) {
                this.videoRef.nativeElement.pause();
            }
        }
    }
}

<div class="video">
    <video class="video__player" loop muted #video>
        <source type="video/mp4" [src]="src">
    </video>

    @if (overlay) {
        <div class="video__overlay"></div>
    }
</div>
