// TypeScript/Edt-Vidt/src/app/views/gridscape/gridscape.component.ts
import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { Actions$ } from '../../../../../Shared/actions/actions';
import { Subject, takeUntil } from 'rxjs';

const AMOUNT_OF_STARS = 40;

@Component({
    selector: 'edt-gridscape',
    templateUrl: './gridscape.component.html',
    styleUrl: './gridscape.component.scss',
})
export class GridscapeComponent implements AfterViewInit, OnDestroy {
    @ViewChild('sun') sunRef?: ElementRef<HTMLElement>;

    public animation?: Animation;

    private readonly destroyed = new Subject();
    stars = new Array(AMOUNT_OF_STARS).fill(0).map((_, i) => i);

    public ngAfterViewInit() {
        this.animation = this.sunRef?.nativeElement.animate(
            [
                {
                    transform: 'translate(-50%, -62%) scale(1)',
                },
                {
                    transform: 'translate(-50%, -62%) scale(1.2)',
                },
                {
                    transform: 'translate(-50%, -62%) scale(1)',
                },
            ],
            {
                easing: 'cubic-bezier(0.215, 0.610, 0.355, 1.000)',
                duration: 200,
            },
        );

        if (this.animation) {
            this.animation.pause();
        }

        Actions$.mainBeat.pipe(takeUntil(this.destroyed)).subscribe(() => {
            this.animate();
        });
    }

    public animate() {
        if (!this.animation) {
            return;
        }
        requestAnimationFrame(() => {
            if (this.animation?.playState === 'running') {
                this.animation.cancel();
            }

            requestAnimationFrame(() => {
                this.animation?.play();
            });
        });
    }

    public ngOnDestroy() {
        this.destroyed.next(true);
        this.destroyed.complete();
    }
}

<div class="gridscape">
    <div class="gridscape__horizon">
        @for (star of stars; track star;) {
            <div class=gridscape__star></div>
        }
        <div class="gridscape__sun" #sun></div>
    </div>
    <div class="gridscape__land">
        <div class="gridscape__lines-horizontal">
            @for (lineHorizontal of [].constructor(10); track 'hor' + lineHorizontal;) {
                <div class="gridscape__line-horizontal" v-for="line in linesHorizontal"></div>
            }
        </div>
        <div class="gridscape__lines-vertical">
            @for (lineVertical of [].constructor(80); track 'vert' + lineVertical;) {
                <div class="gridscape__line-vertical" v-for="line in linesVertical"></div>
            }
        </div>
        <div class="gridscape__overlay"></div>
    </div>
</div>

// TypeScript/edt-vidt2/src/views/gridscape/gridscape.component.vue
<template>
    <div class="gridscape">
        <div class="gridscape__horizon">
            <div class=gridscape__star v-for="star in stars"></div>
            <div class="gridscape__sun" ref="sun">
            </div>
        </div>
        <div class="gridscape__land">
            <div class="gridscape__lines-horizontal">
                <div class="gridscape__line-horizontal" v-for="line in linesHorizontal"></div>
            </div>
            <div class="gridscape__lines-vertical">
                <div class="gridscape__line-vertical" v-for="line in linesVertical"></div>
            </div>
            <div class="gridscape__overlay"></div>
        </div>
    </div>
</template>

<script lang="ts">
    import "./gridscape.scss";
    import Vue from "vue";
    import { Component } from "vue-property-decorator";
    import { Actions$ } from "../../../../Shared/actions";

    @Component
    export default class GridscapeComponent extends Vue {
        public subscription: any;

        public $refs: {
            sun: HTMLElement;
        };

        public linesVertical = Array(80).map((x, i) => i + 1);
        public linesHorizontal = Array(10).map((x, i) => i + 1);
        public stars = Array(40).map((x, i) => i + 1);

        public bounce: boolean = false;
        public animation: Animation;

        mounted() {
            this.animation = this.$refs.sun.animate(
                [
                    {
                        transform: "translate(-50%, -62%) scale(1)",
                    },
                    {
                        transform: "translate(-50%, -62%) scale(1.2)",
                    },
                    {
                        transform: "translate(-50%, -62%) scale(1)",
                    },
                ],
                {
                    easing: "cubic-bezier(0.215, 0.610, 0.355, 1.000)",
                    duration: 200,
                },
            );

            this.animation.pause();

            this.subscription = Actions$.vidtBeat.subscribe(() => {
                this.animate();
            });
        }

        animate() {
            requestAnimationFrame(() => {
                if (this.animation.playState === "running") {
                    this.animation.cancel();
                }

                requestAnimationFrame(() => {
                    this.animation.play();
                });
            });
        }

        destroyed() {
            if (typeof this.subscription !== "undefined") {
                this.subscription.unsubscribe();
            }
        }
    }
</script>
