// Edt-Vidt/src/typescript/presets/hacking/hacking.component.ts
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { stevenCode } from '../../../../../assets/data/stevencode';

@Component({
    name: 'hacking',
    template: require('./hacking.template'),
    components: {
    }
})

export class HackingComponent extends Vue {
    public $refs: {
        text: HTMLElement,
        character: HTMLElement
    };

    public interval: number | undefined;

    mounted() {
        const textArray: string[] = stevenCode.split('');
        let count: number = 0;

        this.interval = window.setInterval(() => {
            if (textArray[count] === "\n") {
                this.$refs.text.appendChild(document.createElement("br"));
            }
            else {
                const element: HTMLElement = document.createElement('span');
                element.classList.add('hacking__character');
                element.innerHTML = textArray[count];
                this.$refs.text.appendChild(element);
            }

            count++;

            if (count === textArray.length) {
                count = 0;
            }

        }, 30);
    }

    destroyed() {
        clearInterval(this.interval);
    }
}

// TypeScript/Edt-Vidt/src/app/views/hacking/hacking.component.ts
import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { stevenCode } from './stevencode';

@Component({
  selector: 'edt-hacking',
  templateUrl: './hacking.component.html',
  styleUrl: './hacking.component.scss'
})
export class HackingComponent implements AfterViewInit, OnDestroy {
    public interval: number | undefined;

    @ViewChild('text') textRef?: ElementRef<HTMLPreElement>;

    public ngAfterViewInit() {
        const textArray: string[] = stevenCode.split('');
        let count: number = 0;

        this.interval = window.setInterval(() => {
            if (textArray[count] === '\n') {
                this.textRef?.nativeElement.appendChild(document.createElement('br'));
            } else {
                const element: HTMLElement = document.createElement('span');
                element.classList.add('hacking__character');
                element.innerHTML = textArray[count];
                this.textRef?.nativeElement.appendChild(element);
            }

            count++;

            if (count === textArray.length) {
                count = 0;
            }
        }, 30);
    }

    public ngOnDestroy() {
        clearInterval(this.interval);
    }
}

<div class='hacking'>
    <pre #text class='hacking__text'></pre>
</div>
