// TypeScript/Edt-Vidt/src/app/views/karaoke/karaoke.component.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { IColor } from '../../../../../Shared/colors/types';
import { ColorHelper } from '../../../../../Shared/colors/converters';
import { Actions$ } from '../../../../../Shared/actions/actions';

@Component({
    selector: 'edt-karaoke',
    templateUrl: './karaoke.component.html',
    styleUrl: './karaoke.component.scss',
})
export class KaraokeComponent implements OnInit, OnDestroy {
    public cssClass: string = '';
    public styles: Object = {};
    public text: string = 'bounce';

    private readonly destroyed = new Subject();

    @ViewChild('text') textRef?: ElementRef<HTMLPreElement>;

    public ngOnInit() {
        Actions$.mainText.pipe(takeUntil(this.destroyed)).subscribe((text) => {
            this.setText(text);
        });

        Actions$.vidtSingleColor.pipe(takeUntil(this.destroyed)).subscribe((color: IColor) => {
            this.setStyles([color]);
        });
    }

    public ngOnDestroy() {
        this.destroyed.next(true);
        this.destroyed.complete();
    }

    public setText(text: string) {
        // if same bounce
        if (this.text === text) {
            this.text = text;
            // wait for text to be in dom
            requestAnimationFrame(() => {
                this.cssClass = 'is-hidden';

                window.setTimeout(() => {
                    this.cssClass = '';
                }, 150);
            });
        } else {
            this.text = text;
        }
    }

    public setStyles(colors: IColor[]) {
        const bcgColor = ColorHelper.getRGBString(colors);

        this.styles = {
            color: `${bcgColor}`,
        };
    }
}

<div class="karaoke">
    <div [class]="cssClass" class="karaoke__inner">
        <p [style]="styles" class="karaoke__text">{{ text }}</p>
    </div>
</div>

// TypeScript/edt-vidt2/src/views/karaoke/karaoke.component.vue
<template>
    <div class="karaoke">
        <div class="karaoke__inner" v-bind:class="cssClass">
            <p class="karaoke__text" v-bind:style="styles">{{ text }}</p>
        </div>
    </div>
</template>

<script lang="ts">
    import "./karaoke.scss";
    import Vue from "vue";
    import { Component } from "vue-property-decorator";
    import { Actions$ } from "../../../../Shared/actions";
    import { IColor } from "../../../../Shared/helpers/types";
    import { ColorHelper } from "../../../../Shared/helpers/hsv-2-rgb";

    const convert = require("color-convert");

    @Component
    export default class KaraokeComponent extends Vue {
        public textSubscription: any;
        public colorSubscription: any;

        public $refs: {
            text: HTMLElement;
        };

        public cssClass: string = "";
        public styles: Object = {};
        public text: string = "bounce";

        mounted() {
            this.textSubscription = Actions$.mainText.subscribe(text => {
                // if same bounce
                if (this.text === text) {
                    this.text = text;
                    // wait for text to be in dom
                    requestAnimationFrame(() => {
                        this.cssClass = "is-hidden";

                        window.setTimeout(() => {
                            this.cssClass = "";
                        }, 150);
                    });
                } else {
                    this.text = text;
                }
            });

            this.colorSubscription = Actions$.vidtSingleColor.subscribe(
                (color: IColor) => {
                    this.setStyles([color]);
                },
            );
        }

        convertToRGB(h: number, s: number, v: number) {
            return convert.hsv.rgb(h, s, v);
        }

        setStyles(colors: IColor[]) {
            const bcgColor = ColorHelper.getRGBString(colors);

            this.styles = {
                color: `${bcgColor}`,
            };
        }

        destroyed() {
            if (typeof this.textSubscription !== "undefined") {
                this.textSubscription.unsubscribe();
            }

            if (typeof this.colorSubscription !== "undefined") {
                this.colorSubscription.unsubscribe();
            }
        }
    }
</script>
