// TypeScript/Edt-Vidt/src/typescript/presets/color-background/color-background.component.ts
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { IColor } from '../../../../../Shared/helpers/types';
import { Actions$ } from '../../../../../Shared/actions';
import { ColorHelper } from '../../../../../Shared/helpers/hsv-2-rgb';

@Component({
    name: 'color-background',
    template: require('./color-background.template'),
    components: {},
})
export class ColorBackgroundComponent extends Vue {
    public singleColorSubscription: any;
    public multiColorSubscription: any;

    public styles: Object = {};

    mounted() {
        this.singleColorSubscription = Actions$.vidtSingleColor.subscribe(
            (color: IColor) => {
                this.setStyles([color]);
            },
        );

        this.multiColorSubscription = Actions$.vidtMultiColor.subscribe(
            (colors: IColor[]) => {
                this.setStyles(colors);
            },
        );
    }

    setStyles(colors: IColor[]) {
        const bcgColor = ColorHelper.getRGBString(colors);
        this.styles = {
            background: `${bcgColor}`
        };
    }

    destroyed() {
        if (typeof this.singleColorSubscription !== 'undefined') {
            this.singleColorSubscription.unsubscribe();
        }

        if (typeof this.multiColorSubscription !== 'undefined') {
            this.multiColorSubscription.unsubscribe();
        }
    }
}

// TypeScript/Edt-Vidt/src/app/views/color-background/color-background.component.ts
import { Component } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { Actions$ } from '../../../../../Shared/actions/actions';
import { IColor } from '../../../../../Shared/colors/types';
import { ColorHelper } from '../../../../../Shared/colors/converters';

@Component({
  selector: 'edt-color-background',
  templateUrl: './color-background.component.html',
  styleUrl: './color-background.component.scss'
})
export class ColorBackgroundComponent {
    public styles: Object = {};

    private readonly destroyed = new Subject();

    public ngOnInit() {
        Actions$.vidtSingleColor
            .pipe(takeUntil(this.destroyed))
            .subscribe((color: IColor) => {
                this.setStyles([color]);
            });

        Actions$.vidtMultiColor.pipe(takeUntil(this.destroyed))
            .subscribe((colors: IColor[]) => {
                this.setStyles([colors[0]]);
            });
    }

    public setStyles(colors: IColor[]) {
        const bcgColor = ColorHelper.getRGBString(colors);
        this.styles = {
            background: `${bcgColor}`,
        };
    }
    public ngOnDestroy() {
        this.destroyed.next(true);
        this.destroyed.complete();
    }
}

<div [style]='styles' class='color-background'></div>
