// TypeScript/Edt-Vidt/src/app/views/photo-glitcher/photo-glitcher.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { Actions$ } from '../../../../../Shared/actions/actions';
import { AnimationTypes } from '../../../../../Shared/vidt/animation';

@Component({
  selector: 'edt-photo-glitcher',
  templateUrl: './photo-glitcher.component.html',
  styleUrl: './photo-glitcher.component.scss'
})
export class PhotoGlitcherComponent implements OnInit, OnDestroy {

    public animation: AnimationTypes = AnimationTypes.bounce;
    public src: string = '';

    private readonly destroyed = new Subject();

    public ngOnInit() {
        Actions$.animationType
            .pipe(takeUntil(this.destroyed))
            .subscribe(animation => {
                this.animation = animation;
            });

        Actions$.imageSrc
            .pipe(takeUntil(this.destroyed))
            .subscribe(photo => {
                this.setSrc(photo);
            });
    }
    public setSrc(src: string) {
        this.src = `./assets/media-by-group/${src}`;
    }

    public ngOnDestroy() {
        this.destroyed.next(true);
        this.destroyed.complete();
    }
}

<div class="photo-glitcher" [class]="'photo-glitcher--' + animation">
    <img class="photo-glitcher__img" #img [src]="src" alt="">
</div>

// Edt-Vue-Vidt/src/typescript/presets/photo-glitcher/photo-glitcher.component.ts
import Vue from 'vue';
import {Component} from 'vue-property-decorator';
import {photoAssets} from '../../../../../Shared/assets';
import {Actions$} from '../../../../../Shared/actions';
import {animationTypes} from '../../../../../Shared/vidt-presets';

@Component({
    name: 'photo-glitcher',
    template: require('./photo-glitcher.template'),
    components: {
    }
})

export class PhotoGlitcherComponent extends Vue {
    public animationSubscription: any;
    public photoSubscription: any;

    public animation: string = 'bounce';
    public src: string = '';

    mounted() {
        this.setSrc(photoAssets[0].src);

        this.animationSubscription = Actions$.animationType
            .subscribe((animation) => {
                this.animation = animationTypes[animation];
            });

        this.photoSubscription = Actions$.imageSrc
            .subscribe((photo) => {
                this.setSrc(photo.src);
            });
    }

    setSrc(src: string) {
        this.src = `assets/img/photoassets/${src}`;
    }

    destroyed() {
        if (typeof this.animationSubscription !== 'undefined') {
            this.animationSubscription.unsubscribe();
        }

        if (typeof this.photoSubscription !== 'undefined') {
            this.photoSubscription.unsubscribe();
        }
    }
}
